export const initialCarData={
    id: "",
    make: "",
    model: "",
    year: 0,
    engineType: "",
    gearBox: "",
    condition: "",
    horsePower:0,
    color: "",
    price: 0,
    city: "",
    mileage: 0,
    user:{id: '',
      username: '',
      firstName: '',
      lastName: '',
      password: null},
    extras: "",
  };